# site properties and page defaults
title: NVL-Lab
subtitle: 
description: We use neuroprosthetics to study the brain and apply what we learn to improve neuroprosthetics.
header: images/banner_lab.png
footer: images/banner_lab.png
show-title: false
show-subtitle: false

# site social media and other links
links:
  email: nuria.vendrell.llopis@gmail.com
  orcid: 0000-0002-8618-4247
  google-scholar: SWorGjsAAAAJ
  github: NVL-Lab
  twitter: VendrellLlopis
  youtube: NVL-Lab

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
